### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by cmonopop** [3santree/icecold#1]
when i run go run .
i don't get the a.exe in output folder

**Comment by 3santree** [comment]
Could you provide more info to help you to debug? Your system? error message etc

**Comment by 3santree** [comment]
Issue's been fixed, I've forget to upload the `output` folder, let me you if you find any issue.

**Comment by cmonopop** [comment]
on running go run .
i don't get anything on terminal(no error and no output)

**Comment by 3santree** [comment]
You're right, you probably run it on linux, which I didn't test before. Before I fixed it, you can try compile it using command `GOOS=windows GOARCH=amd64 go build -o output/a.exe template/main.go`. It will compile it and output to the `output` folder.

**Comment by 3santree** [comment]
> on running go run . i don't get anything on terminal(no error and no output)

I've added the env variable need for linux into the code, now you can try it on your system see if it's work this time!

**Comment by cmonopop** [comment]
okay 
and in what format can i give a cs generated bin file??

**Comment by 3santree** [comment]
> okay and in what format can i give a cs generated bin file??

I may not understand your question correctly, plz correct me with more info on your question if I'm wrong.
If your `cs` means cobaltstrike, and you want generate an executable that integrate cobalt strike, and give you a shell after executing the exe, you need to replace the shellcode with the one cobalt strike generated for you.
If your `cs` means C sharp, and you want to generate a exe that follows the format what C# would generate, i don't think it's possible because golang compile the code differently, however, they are all PE file.

**Comment by cmonopop** [comment]
yea i meant to say about the beacon generated from cobalt strike
so how shall i use the raw shellcode of cobalt strike with icecold?

**Comment by cmonopop** [comment]
do i have to convert the generated shellcode into hex using xxd?
and in which format?(like 0x or \x)
and then where should i replace the converted shellcode to hex format in the main.go

**Comment by 3santree** [comment]
the shellcode need to be in format of byte slice in golang, the variable should be something like []byte{0x01, 0x12, 0xaa}, I suggest to try out golang first if you are not familiar with it.
For the location to replace the shellcode, you can see in the `Usage` part of  README.md
